### ISSUE TITLE
issues logging in

### ISSUE THREAD

**Issue by boredomdenied** [lefta/examshell42#1]
I'm at 42 SV campus working off my laptop. Have successfully installed examshell; however I get `You do not have a valid Kerberos ticket..` attempting `kinit username@42.US.ORG` times out. Any suggestions on how to remedy this?

**Comment by lefta** [comment]
I would at first recommend that you pull the latest examshell version from the school Macs, this one is likely outdated. If you do so, feel free to PR the new python egg if you manage to get it working.

About the problem itself : at a first glance, I would bet on two reasons for the timeout : 
* You are not connected in the school network. AFAIK, the kerberos server is not exposed outside the school.
* You did not setup kerberos for 42. Yes, there is (was?) some setup required for it. The only one that I know about is this one : https://github.com/colundrum/42_vogsphere_access. However, it is also quite old, and may or may not work. And it is made for the campus of Paris, I'm not sure it will work at 42 US. I would recommend that you check the configuration files on a school Mac and copy it to yours. Relevant files are `/etc/krb5.conf`, `/etc/ssh/ssh_config`, and `~/.ssh/config`.

Note that I'm not in the school anymore, I can't test anything myself. I will still try my best to get you running, but I can't promise anything...

**Comment by boredomdenied** [comment]
Thank you for the comment. I have successfully established kerberos tickets showing 3 when using examshell. The issue came from using a hackintosh laptop which assigned `en0` network interface to the bluetooth adapter and `en1` for the wifi. I found the relevant plist file and swapped out the values in 3 spots for each interface. 

All is well now.

**Comment by lefta** [comment]
Nice, I would never have guessed it. I'm closing the ticket now that it's fixed.
